name: "Add JIRA link"
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: get PR title
      - run: echo ${{ github.event.pull_request.title }}
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            The title is: ${{ github.event.pull_request.title }}
