name: "Add JIRA link"
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: get PR title
        # extract ticket number out of the title
        run: echo "TICKET_NUMBER=${(${{ github.event.pull_request.title }} | cut -f 1 -d ' ' | sed 's/\[//g' | sed 's/\]//g')}" >> $GITHUB_ENV
      - name: echo PR title
        run: echo $TICKET_NUMBER
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            The title is: ${{ github.event.pull_request.title }}
