name: "Add JIRA link"
on: pull_request
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: get JIRA ticket number
        # extract ticket number out of the title
        run: echo "TICKET_NUMBER=$(echo ${{ github.event.pull_request.title }} | cut -f 1 -d ' ' | sed 's/\[//g' | sed 's/\]//g')" >> $GITHUB_ENV
      - name: echo JIRA ticket number
        run: echo $TICKET_NUMBER
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}, we found a JIRA ticket for you!
          JIRA link: [${{ env.TICKET_NUMBER }}](https://www.google.com)
