name: "Check PR branch name"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{contains(github.head_ref, 'release')}}
      - name: check1
        if: startsWith(github.head_ref, 'feature,bugfix,hotfix')
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '(LEV|LW)-[0-9]+-\S+'

      - name: check2
        if: startsWith(github.head_ref, 'release')
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: 'v[0-9]+.[0-9]+.[0-9]+'

      - name: fallback
        run: exit 1
