name: "Check PR branch name"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: check1
        continue-on-error: true
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '(LEV|LW)-[0-9]+-\S+'
          allowed_prefixes: 'feature,bugfix,hotfix'
          ignore: main,develop

      - name: check2
        continue-on-error: true
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: 'v\.[0-9]+.[0-9]+.[0-9]+'
          allowed_prefixes: 'release'
          ignore: main,develop

      - name: test
        run: |
          echo ${{steps.check1.outcome}}
          echo ${{steps.check2.outcome}}
          echo ${{steps.check1.conclusion}}
          echo ${{steps.check2.conclusion}}

      - name: result
        if: always() && (steps.check1.outcome == 'success' || steps.check2.outcome == 'success')
        run: exit 0
