name: "Check PR branch name"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: check1
        if: contains('refs/heads/feature,refs/heads/bugfix,refs/heads/hotfix', github.ref)
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '(LEV|LW)-[0-9]+-\S+'

      - name: check2
        if: contains('refs/heads/release', github.ref)
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: 'v\.[0-9]+.[0-9]+.[0-9]+'

      - name: fallback
        run: exit 1
