name: "PR check"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  feature-or-fix-branch-naming-rules:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature,bugfix,hotfix')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/(LEV|LW)-[0-9]+-\S+'
          allowed_prefixes: 'feature,bugfix,hotfix'

  release-branch-naming-rules:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/v[0-9]+.[0-9]+.[0-9]+'
          allowed_prefixes: 'release'

  creative-friday-branch-naming-rules:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'creative-friday')
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '[a-z]+\/\S+'
          allowed_prefixes: 'creative-friday'

  unknown-branch-naming-rules:
    needs: [feature-or-fix-branch-naming-rules, release-branch-naming-rules, creative-friday-branch-naming-rules]
    runs-on: ubuntu-latest
    if: jobs.feature-or-fix-branch-naming-rules.outcome == 'skipped' && jobs.release-branch-naming-rules.outcome == 'skipped' && jobs.creative-friday-branch-naming-rules.outcome == 'skipped'
    steps:
      - run: |
          cat <<'END'
          Branch name does not adhere to standards. Following branch name patterns are allowed:
            (bugfix|hotfix|feature)/(LW|LEV)-NUMBER-description
            release/vX.Y.Z
            creative-friday/description
          END
          exit 1

  title-check:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature,bugfix,hotfix')
    steps:
      - uses: thehanimo/pr-title-checker@v1.3.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          configuration_path: ".github/pr-title-checker-config.json"

  insert-jira-link:
    runs-on: ubuntu-latest
    needs: title-check
    steps:
      - name: get JIRA ticket number
        # extract JIRA ticket number out of the title
        run: echo "JIRA_TICKET_NUMBER=$(echo ${{ github.event.pull_request.title }} | cut -f 1 -d ' ' | sed 's/\[//g' | sed 's/\]//g')" >> $GITHUB_ENV
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            We found a JIRA ticket for you!
            JIRA link: [${{ env.JIRA_TICKET_NUMBER }}](https://levelworks.atlassian.net/browse/${{ env.JIRA_TICKET_NUMBER }})
